apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  annotations:
  name: rsm
  namespace: rsm-001
spec:
  maxReplicas: 6
  minReplicas: 3
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: rsm
  targetCPUUtilizationPercentage: 20
