apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
  labels:
    run: rsm
  name: rsm
  namespace: rsm-001
spec:
  replicas: 3
  selector:
    matchLabels:
      run: rsm
  strategy:
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: rsm
    spec:
      containers:
      - image: kanedafromparis/resourcesmonger:1.0
        imagePullPolicy: Always
        name: rsm
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: 2500m
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 256Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 5
