apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 
  labels:
    run: rsm
  name: rsm
  namespace: rsm-001
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    run: rsm
  sessionAffinity: None
  type: LoadBalancer
